export enum ItemsType {
    ELECTRONICS = 'ELECTRONICS',
    JEWELLERY = 'JEWELLERY',
    HEALTH_CARE = 'HEALTH_CARE',
    GARMENTS = 'GARMENTS',
    LITHIUM_BATTERY = 'LITHIUM_BATTERY',
    OTHERS = 'OTHERS'
}
